name: Sync Board Texts

#0 0 * * * 
on:
    schedule:
      - cron: "0 0 * * *"   #Every Day at Midnight
      - cron: "*/30 * * * SUN"   #Every 30 minutes, only on Sunday
      
    workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch Board String (GMT)
      id: gmt-boardtext
      run: |
        {
            echo 'WHITEBOARD<<EOF'
            curl https://whiteboard-diczrrhb6a-uc.a.run.app/?path=gmt
            echo EOF
        } >> "${GITHUB_OUTPUT}"


    - name: Modify GMT Text
      uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: TimesGMT.txt
        body: "${{ steps.gmt-boardtext.outputs.WHITEBOARD }}"
        overwrite: 'true'

    - name: Fetch Board String (AU)
      id: au-boardtext
      run: |
        {
            echo 'WHITEBOARD<<EOF'
            curl https://whiteboard-diczrrhb6a-uc.a.run.app/?path=au
            echo EOF
        } >> "${GITHUB_OUTPUT}"


    - name: Modify AU Text
      uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: TimesAU.txt
        body: "${{ steps.au-boardtext.outputs.WHITEBOARD }}"
        overwrite: 'true'
