name: Sync Board Texts

#0 0 * * * 
on:
    schedule:
      - cron: "0 0 * * *"   #Every Day at Midnight
      
    workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch Board String (GMT)
      run: boardtext="$(curl https://whiteboard-diczrrhb6a-uc.a.run.app/?path=gmt)"; echo "boardtext=$boardtext" >> "${GITHUB_OUTPUT}"
      id: gmt-boardtext

    - name: Modify README.md
      uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: TimeGMT.txt
        body: "${{ steps.gmt-boardtext.outputs.status }}"
        overwrite: 'true'
